title: Parth Batra | fromparth.blog
author: Parth Batra
email: hi@fromparth.blog
baseurl: ""
url: "https://fromparth.blog"
twitter_username: batra99
github_username: parthbatra99
linkedin_username: parth-batra99
description: Senior ML Engineer by day, music critic by night. Building ML systems, writing about tech, and collecting spotify minutes like they're infinity stones.

theme: minima
plugins:
  - jekyll-toc

exclude:
  - scripts/

